server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/customers/**
        - id: accounts-service
            uri: lb://accounts-service
            predicates:
              - Path=/accounts/**